services:

  solarwatch_db:
      image: 'postgres:17.4-alpine3.21'
      container_name: solarwatch_db
      environment:
        - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
        - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - POSTGRES_DB=solarwatch
      volumes:
        - solarwatch_postgres_data:/var/lib/postgresql/data
      networks:
        - solarwatch_network

  solarwatch_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solarwatch_backend
    depends_on:
      - solarwatch_db
    environment:
      - API_KEY=${API_KEY}
      - GEOCODING_BASE_URL=${GEOCODING_BASE_URL}
      - SUNRISESUNSET_BASE_URL=${SUNRISESUNSET_BASE_URL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - jwt.secret=${JWT_SECRET}
      - jwtExpirationMs=${JWT_EXPIRATION_MS}
    networks:
      - solarwatch_network
  solarwatch_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solarwatch_frontend
    ports:  
    - "3000:80"
    depends_on:
      - solarwatch_backend
    networks:
      - solarwatch_network
    
volumes:
  solarwatch_postgres_data:

networks:
  solarwatch_network:
